### ISSUE TITLE
Requires migrate version 2.6-beta1 or above

### ISSUE THREAD

**Issue by adixon** [eileenmcnaughton/civimigrate#10]
Even though migrate 2.5 is still the default/recommended version.

**Comment by eileenmcnaughton** [comment]
where is the migrate version specified?

**Comment by adixon** [comment]
I'm not sure what your question is ... there was an architectural change from 2.5 to 2.6 that it looks like your code is making use of, and something wasn't working when I used 2.5.

In any case, 2.6 is better and you probably want to specify one of them since they are different in subtle ways and trying to support both will be tricky.

Or, if your question is about where is the migrate version specified in your code, then the answer is that it isn't - when I'm saying that the default/recommended version of migrate is 2.5, I'm referring to the migrate module itself on drupal.org.

**Comment by eileenmcnaughton** [comment]
Just pushed a commit which I think is what you mean

**Comment by adixon** [comment]
exactly!
