### ISSUE TITLE
Update your example module?

### ISSUE THREAD

**Issue by adixon** [eileenmcnaughton/civimigrate#8]
I think you've updated some bits without updating what used to be your super-useful example module, e.g. the __construct function now needs an argument.

**Comment by eileenmcnaughton** [comment]
seems to be this commit

https://github.com/eileenmcnaughton/civimigrate/commit/aeb18bd48e7e47141d60eec9e3c19a81fc79c245#diff-78c65ff868016c6e8a8c2d218e485c50

**Comment by eileenmcnaughton** [comment]
Fixed -

**Comment by eileenmcnaughton** [comment]
hmm - I think all bets are off if your migrate version is less than 7.x-2.6-rc1
