### ISSUE TITLE
changes to the civicrm api in the most recent-ish 4.3 series?

### ISSUE THREAD

**Issue by adixon** [eileenmcnaughton/civimigrate#9]
I had a version of your code working reasonably for an earlier version of civicrm 4.3 (Drupal 7) and now I'm getting batch errors for 4.3.8 that make me think there's been a change a return value or something in the civicrm api that breaks it - it was for the getsingle request I think. Does that ring a bell for you?

**Comment by eileenmcnaughton** [comment]
hmm - did I switch civimigrate from civicrm-api to civicrm_api3? if so then there was one 4.3 release that didn't work with it - but - do you have the errors?

**Comment by adixon** [comment]
Sorry, yes:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: /batch?id=5&op=do StatusText: OK ResponseText: Array ( [count] => 0 [is_error] => 1 [error_message] => Expected one contact but found 0 )

If that doesn't look familiar, then it's probably something I did, I was just hoping for a clue before digging back into the guts.

**Comment by eileenmcnaughton** [comment]
Did you get to the bottom of this - setting $this->debug = 1 is pretty handy. I can't see any obvious reason

**Comment by adixon** [comment]
yes, I think whatever was going on was self-inflicted.

On Wed, Feb 26, 2014 at 6:33 AM, Eileen McNaughton <notifications@github.com

> wrote:
> 
> Did you get to the bottom of this - setting $this->debug = 1 is pretty
> handy. I can't see any obvious reason
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/eileenmcnaughton/civimigrate/issues/9#issuecomment-36116082
> .

## 

Alan Dixon, Web Developer

Drupal and CiviCRM for Canadian nonprofits.
http://blackflysolutions.ca/

**Comment by eileenmcnaughton** [comment]
good luck with it then!
